version: '3'
services:
  web:
    build: 
      context: ./
      dockerfile: php.Dockerfile
    container_name: webserver
    depends_on: 
      - database
    volumes: 
      - ./:/var/www/html/
    ports: 
      - '80:80'
    networks:
      - webnet

  database:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Beacon
      MYSQL_USER: Geniuses
      MYSQL_PASSWORD: cs411
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      MYSQL_USER: Geniuses
      MYSQL_PASSWORD: cs411
      MYSQL_ROOT_PASSWORD: root
    networks:
      - webnet

networks:
  webnet: